# `Hallmark` Demo

This Jupyter notebook demonstrates how `hallmark` is used.

In [75]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Remove Old Demo Repositories

First, let's remove all old demo repositories.

In [76]:
! rm -rf repo*

## Initialize a Standard (Non-Bare) `Hallmark` Repository

`Hallmark` is similar to `git`.
To create an empty (standard) `hallmark` repository, we call `hallmark.Repo.init(REPO)`.

In [77]:
from hallmark import Repo

repo1 = Repo.init("repo1")

Check the content of the hallmark repository.
It contains a ".hm" directory, which is itself a git repository.

In [78]:
! ls -a repo1 repo1/.hm

repo1:
.  ..  .hm

repo1/.hm:
.  ..  .git  README.md	config.yml  data.tsv  meta.yml

We can `cd` into the ".hm" directory and then run `git`.
However, because `cd` is not a very good practice in Jupyter notebook,
we will use `pushd` and `popd` instead.

In [79]:
! pushd repo1/.hm && git status && popd

~/EHT/hallmark/demo/repo1/.hm ~/EHT/hallmark/demo
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   config.yml
	new file:   data.tsv
	new file:   meta.yml

~/EHT/hallmark/demo

Note, similar to `git init`, `hallmark.Repo.init()` does not commit your files.

## Initialize a Bare Hallmark Repository

Next, we will initialize a bare repository.
Unlikely `git`, all we need is to explicitly postfix ".hm" to the repository name.

In [80]:
repo2 = Repo.init("repo2.hm")

`repo2.hm` is itself a `git` repository.

In [81]:
! ls -a repo2.hm

.  ..  .git  README.md	config.yml  data.tsv  meta.yml

In [82]:
! pushd repo2.hm && git status && popd

~/EHT/hallmark/demo/repo2.hm ~/EHT/hallmark/demo
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   config.yml
	new file:   data.tsv
	new file:   meta.yml

~/EHT/hallmark/demo

## Add Files According to Python Format String

In [83]:
! pushd repo1 && touch a{0,0.75,0.94}_i{0..180..30}.h5 && popd
! ls repo1

~/EHT/hallmark/demo/repo1 ~/EHT/hallmark/demo
~/EHT/hallmark/demo
a0.75_i0.h5    a0.75_i30.h5  a0.94_i120.h5  a0.94_i60.h5  a0_i150.h5  a0_i90.h5
a0.75_i120.h5  a0.75_i60.h5  a0.94_i150.h5  a0.94_i90.h5  a0_i180.h5
a0.75_i150.h5  a0.75_i90.h5  a0.94_i180.h5  a0_i0.h5	  a0_i30.h5
a0.75_i180.h5  a0.94_i0.h5   a0.94_i30.h5   a0_i120.h5	  a0_i60.h5

In [84]:
repo1.add("a{a}_i{i}.h5")

             path     a      i                                      sha1
0     a0.75_i0.h5  0.75    0.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
1   a0.75_i120.h5  0.75  120.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
2   a0.75_i150.h5  0.75  150.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
3   a0.75_i180.h5  0.75  180.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
4    a0.75_i30.h5  0.75   30.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
5    a0.75_i60.h5  0.75   60.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
6    a0.75_i90.h5  0.75   90.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
7     a0.94_i0.h5  0.94    0.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
8   a0.94_i120.h5  0.94  120.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
9   a0.94_i150.h5  0.94  150.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
10  a0.94_i180.h5  0.94  180.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
11   a0.94_i30.h5  0.94   30.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
12   a0.94_i60.h5  0.94   60.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
13   a0.94_i90.h5  0.94   90.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
14       a0_i0.h5  0.00    0.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
15     a0_i120.h5  0.00  120.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
16     a0_i150.h5  0.00  150.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
17     a0_i180.h5  0.00  180.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
18      a0_i30.h5  0.00   30.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
19      a0_i60.h5  0.00   60.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
20      a0_i90.h5  0.00   90.0  da39a3ee5e6b4b0d3255bfef95601890afd80709

In [85]:
repo1.commit("Commit test")

True

## Use Case with Encoding

In [86]:
%%bash
pushd repo1

touch am0.75_i0.h5 \
      am0.75_i30.h5 \
      am0.75_i60.h5 \
      am0.94_i0.h5 \
      am0.94_i30.h5 \
      am0.94_i+30.h5 \
      am0.94_i60.h5

popd

~/EHT/hallmark/demo/repo1 ~/EHT/hallmark/demo
~/EHT/hallmark/demo

In [87]:
%%bash
cat > repo1/.hm/config.yml <<'EOF'
encodings:
  - fmt: "a{aspin}_i{i}.h5"
    encoding:
      aspin: "m([0-9]+(\\.[0-9]+)?)"
EOF

In [88]:
repo1.state.config = repo1.dothm.load_yml("config")

In [89]:
repo1.add("a{aspin}_i{i}.h5", encoding=True)

              path  aspin      i                                      sha1
0      a0.75_i0.h5   0.75    0.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
1    a0.75_i120.h5   0.75  120.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
2    a0.75_i150.h5   0.75  150.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
3    a0.75_i180.h5   0.75  180.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
4     a0.75_i30.h5   0.75   30.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
5     a0.75_i60.h5   0.75   60.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
6     a0.75_i90.h5   0.75   90.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
7      a0.94_i0.h5   0.94    0.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
8    a0.94_i120.h5   0.94  120.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
9    a0.94_i150.h5   0.94  150.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
10   a0.94_i180.h5   0.94  180.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
11    a0.94_i30.h5   0.94   30.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
12    a0.94_i60.h5   0.94   60.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
13    a0.94_i90.h5   0.94   90.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
14        a0_i0.h5   0.00    0.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
15      a0_i120.h5   0.00  120.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
16      a0_i150.h5   0.00  150.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
17      a0_i180.h5   0.00  180.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
18       a0_i30.h5   0.00   30.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
19       a0_i60.h5   0.00   60.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
20       a0_i90.h5   0.00   90.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
21    am0.75_i0.h5  -0.75    0.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
22   am0.75_i30.h5  -0.75   30.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
23   am0.75_i60.h5  -0.75   60.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
24  am0.94_i+30.h5  -0.94   30.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
25    am0.94_i0.h5  -0.94    0.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
26   am0.94_i30.h5  -0.94   30.0  da39a3ee5e6b4b0d3255bfef95601890afd80709
27   am0.94_i60.h5  -0.94   60.0  da39a3ee5e6b4b0d3255bfef95601890afd80709